language: cpp

before_install:
  - sudo apt-get update -qq

install:
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -y g++; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -y clang; fi

before_script:
  - if [ "$CXX" == "g++" ]; then g++ --version; fi
  - if [ "$CXX" == "clang++" ]; then clang++ --version; fi
  - mkdir build
  - cd build
  - cmake ..
  - make

script: make test

os:
  - linux
